Bump node version

diff --git a/.github/workflows/gatsby.yml b/.github/workflows/gatsby.yml
--- a/.github/workflows/gatsby.yml
+++ b/.github/workflows/gatsby.yml
@@ -24,57 +24,57 @@ jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Detect package manager
-        id: detect-package-manager
-        run: |
-          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "::set-output name=manager::yarn"
-            echo "::set-output name=command::install"
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "::set-output name=manager::npm"
-            echo "::set-output name=command::ci"
-            exit 0
-          else
-            echo "Unable to determine packager manager"
-            exit 1
-          fi
-      - name: Setup Node
-        uses: actions/setup-node@v3
-        with:
-          node-version: "16"
-          cache: ${{ steps.detect-package-manager.outputs.manager }}
-      - name: Restore cache
-        uses: actions/cache@v3
-        with:
-          path: |
-            public
-            .cache
-          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('public') }}
-          restore-keys: |
-            ${{ runner.os }}-gatsby-build-
-      - name: Install dependencies
-        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
-      - name: Build with Gatsby
-        env:
-          PREFIX_PATHS: 'true'
-        run: ${{ steps.detect-package-manager.outputs.manager }} run build
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
-      - name: Deploy Gatsby to AWS S3
-        uses: jonelantha/gatsby-s3-action@v1
-        with:
-          # Destination S3 Bucket
-          dest-s3-bucket: pradyumnashome.com
-          # Browser cache duration (sec) for cache control headers
-          browser-cache-duration: 7890000
-          # CDN cache duration (sec) for cache control headers (sec)
-          cdn-cache-duration: 7890000
-          # Cloudfront ID to invalidate
-          cloudfront-id-to-invalidate: E2GNF2ZJTU2DX5 # optional
+    - name: Checkout
+      uses: actions/checkout@v3
+    - name: Detect package manager
+      id: detect-package-manager
+      run: |
+        if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+          echo "::set-output name=manager::yarn"
+          echo "::set-output name=command::install"
+          exit 0
+        elif [ -f "${{ github.workspace }}/package.json" ]; then
+          echo "::set-output name=manager::npm"
+          echo "::set-output name=command::ci"
+          exit 0
+        else
+          echo "Unable to determine packager manager"
+          exit 1
+        fi
+    - name: Setup Node
+      uses: actions/setup-node@v3
+      with:
+        node-version: "18.8.0"
+        cache: ${{ steps.detect-package-manager.outputs.manager }}
+    - name: Restore cache
+      uses: actions/cache@v3
+      with:
+        path: |
+          public
+          .cache
+        key: ${{ runner.os }}-gatsby-build-${{ hashFiles('public') }}
+        restore-keys: |
+          ${{ runner.os }}-gatsby-build-
+    - name: Install dependencies
+      run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+    - name: Build with Gatsby
+      env:
+        PREFIX_PATHS: 'true'
+      run: ${{ steps.detect-package-manager.outputs.manager }} run build
+    - name: Configure AWS Credentials
+      uses: aws-actions/configure-aws-credentials@v1
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws-region: us-east-1
+    - name: Deploy Gatsby to AWS S3
+      uses: jonelantha/gatsby-s3-action@v1
+      with:
+        # Destination S3 Bucket
+        dest-s3-bucket: pradyumnashome.com
+        # Browser cache duration (sec) for cache control headers
+        browser-cache-duration: 7890000
+        # CDN cache duration (sec) for cache control headers (sec)
+        cdn-cache-duration: 7890000
+        # Cloudfront ID to invalidate
+        cloudfront-id-to-invalidate: E2GNF2ZJTU2DX5 # optional
